config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'find_workout' => 'static_pages#find_workout'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :relationships, only: [:create, :destroy]
  
  resources :workouts, only: [:create, :destroy]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= current_user.geography %></span>
<span><%= pluralize(current_user.workouts.count, "workout") %></span>

app/views/shared/_workout_feed.html.erb
<% if @workout_feed_items.any? %>
  <ol class="microposts">
    <%= render @workout_feed_items %>
  </ol>
  <%= will_paginate @workout_feed_items %>
<% end %>

app/views/shared/_workout_form.html.erb
<%= form_for(@workout) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :activity, placeholder: "Compose new workout..." %>
  </div>

  <%= f.label :location %>
  <%= f.text_field :location, class: 'form-control' %> 

	<%= f.label :activity_time %>
  <%= f.datetime_local_field :activity_time, class: 'form-control' %>
  
  <%= f.submit "Post", class: "btn btn-primary" %>
  
<% end %>